news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.articulo-titulo a'
      article_body: '.articulo-cuerpo'
      article_title: '.articulo-titulo' 
  washingtonpost:
    url: https://www.washingtonpost.com
    queries:
      homepage_article_links: '.headline a'
      article_body: '.topper-headline h1'
      article_title: 'article.paywall'

